___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

<img src=https://i.ibb.co/wJW61Y2/Used-cars.jpg width="700" height="200">

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">The Capstone Project of Data Analytics Module</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:150%; text-align:center; border-radius:10px 10px;">Car Price Prediction EDA</p>

## Introduction
Welcome to "***AutoScout Data Analysis Project***". This is the capstone project of ***Data Analysis*** Module. **Auto Scout** data which using for this project, scraped from the on-line car trading company in 2019, contains many features of 9 different car models. In this project, you will have the opportunity to apply many commonly used algorithms for Data Cleaning and Exploratory Data Analysis by using many Python libraries such as Numpy, Pandas, Matplotlib, Seaborn, Scipy you will analyze clean dataset.

### Some Reminders on Exploratory data analysis (EDA)

Exploratory data analysis (EDA) is an especially important activity in the routine of a data analyst or scientist. It enables an in depth understanding of the dataset, define or discard hypotheses and create predictive models on a solid basis. It uses data manipulation techniques and several statistical tools to describe and understand the relationship between variables and how these can impact business. By means of EDA, we can obtain meaningful insights that can impact analysis under the following questions (If a checklist is good enough for pilots to use every flight, it’s good enough for data scientists to use with every dataset).
1. What question are you trying to solve (or prove wrong)?
2. What kind of data do you have?
3. What’s missing from the data?
4. Where are the outliers?
5. How can you add, change or remove features to get more out of your data?

**``Exploratory data analysis (EDA)``** is often an **iterative brainstorming process** where you pose a question, review the data, and develop further questions to investigate before beginning model development work. The image below shows how the brainstorming phase is connected with that of understanding the variables and how this in turn is connected again with the brainstorming phase.<br>

<img src=https://i.ibb.co/k0MC950/EDA-Process.png width="300" height="100">

[Image Credit: Andrew D.](https://towardsdatascience.com/exploratory-data-analysis-in-python-a-step-by-step-process-d0dfa6bf94ee)

**``In this context, the project consists of 3 parts in general:``**
* **The first part** is related to 'Data Cleaning'. It deals with Incorrect Headers, Incorrect Format, Anomalies, and Dropping useless columns.
* **The second part** is related to 'Filling Data', in other words 'Imputation'. It deals with Missing Values. Categorical to numeric transformation is done as well.
* **The third part** is related to 'Handling Outliers of Data' via Visualization libraries. So, some insights will be extracted.

**``NOTE:``**  However, you are free to create your own style. You do NOT have to stick to the steps above. Nevertheless, we, the DA & DV instructors, recommend you study each part separately to create a source notebook for your further studies.

In [537]:
        import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [538]:
df = pd.read_json("scout_car.json", lines=True)

KeyboardInterrupt:

# PART- 0 `( Explore Data)`

In [ ]:
df.head()

In [ ]:
df.shape

In [ ]:
df.columns

In [ ]:
df.info()

In [ ]:
df.url

In [ ]:
df.make_model.value_counts(dropna=True)

In [ ]:
df.short_description.value_counts(dropna=False)

In [ ]:
df.short_description.unique()

In [ ]:
df.body_type.value_counts(dropna=False)

In [ ]:
df.body_type.unique()

In [ ]:
df.vat.value_counts(dropna=False)

In [ ]:
df.vat.isnull().sum()

In [ ]:
df.km.isnull().sum()

In [ ]:
df.km.value_counts(dropna=False)

In [ ]:
df.registration.value_counts(dropna=False)
##df.registration.isnull().sum()

In [ ]:
df.hp.value_counts(dropna=False)
##df.hp.isnull().sum()

In [ ]:
df.Type.value_counts(dropna=False)
##df.type.isnull().sum()

In [ ]:
df["Previous Owners"].value_counts(dropna=False)
##df.type.isnull().sum()

In [ ]:
df["Next Inspection"].value_counts(dropna=False)
##df.type.isnull().sum()

In [ ]:
df["Inspection new"].value_counts(dropna=False)
##df.type.isnull().sum()

In [ ]:
df["Warranty"].value_counts(dropna=False)

In [ ]:
df["Full Service"].value_counts(dropna=False)

In [ ]:
df["Non-smoking Vehicle"].value_counts(dropna=False)

In [ ]:
df["null"].value_counts(dropna=False)

In [ ]:
df["Make"].value_counts(dropna=False)

In [ ]:
df["Model"].value_counts(dropna=False)

In [ ]:
df["Model"].nunique

In [ ]:
df["Offer Number"].head(10)

In [ ]:
df["First Registration"].value_counts(dropna=False)

In [ ]:
df["Body Color"].value_counts(dropna=False)

In [ ]:
df["Paint Type"].value_counts(dropna=False)

In [ ]:
df["Body Color Original"].value_counts(dropna=False)

In [ ]:
df["Upholstery"].value_counts(dropna=False)

In [ ]:
df["Body"].value_counts(dropna=False)

In [ ]:
df["Nr. of Doors"].value_counts(dropna=False)

In [ ]:
df["Nr. of Seats"].value_counts(dropna=False)

In [ ]:
df["Model Code"].value_counts(dropna=False)

In [ ]:
df["Model Code"].unique

In [ ]:
df["Gearing Type"].value_counts(dropna=False)

In [ ]:
df["Displacement"].value_counts(dropna=False)

In [ ]:
df["Cylinders"].value_counts(dropna=False)

In [ ]:
df["Weight"].value_counts(dropna=False)

In [ ]:
df["Drive chain"].value_counts(dropna=False)

In [ ]:
df["Fuel"].value_counts(dropna=False)

In [ ]:
df["Consumption"].value_counts(dropna=False)

In [ ]:
df["CO2 Emission"].value_counts(dropna=False)

In [ ]:
df["Emission Class"].value_counts(dropna=False)

In [ ]:
df['\nComfort & Convenience\n'].value_counts(dropna=False)

In [ ]:
df['\nEntertainment & Media\n'].value_counts(dropna=False)

In [ ]:
df['\nExtras\n'].value_counts(dropna=False)

In [ ]:
df['\nSafety & Security\n'].value_counts(dropna=False)

In [ ]:
df['description'].value_counts(dropna=False)

In [ ]:
df['Emission Label'].value_counts(dropna=False)

In [ ]:
df['Gears'].value_counts(dropna=False)

In [ ]:
df['Country version'].value_counts(dropna=False)

In [ ]:
df['Electricity consumption'].value_counts(dropna=False)

In [ ]:
df['Last Service Date'].value_counts(dropna=False)

In [ ]:
df['Other Fuel Types'].value_counts(dropna=False)

In [ ]:
df['Availability'].value_counts(dropna=False)

In [ ]:
df['Last Timing Belt Service Date'].value_counts(dropna=False)

In [ ]:
df['Available from'].value_counts(dropna=False)

# PART- 1 `( Data Cleaning )`

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_json("scout_car.json", lines=True)

In [ ]:
df.info()

In [ ]:
df.columns

In [ ]:
my_list = []
for i in df.columns:
    my_list.append(i.lower().replace('-','_').replace(' ', '_').replace('.', '').replace('&', '').replace('\n', '' ).replace('__', '_'))
print(my_list)

In [ ]:
df.columns = my_list
df.columns

In [ ]:
df.make_model.value_counts()

In [ ]:
df["make1"] = df.make_model.str.split(' ').str[0]

In [ ]:
df.make1.value_counts()

In [ ]:
df["model1"] = df['make_model'].str.split(' ').str[1]

In [ ]:
df.model1.value_counts()

In [ ]:
df.vat.value_counts(dropna=False)

In [ ]:
df.vat.replace('NULL', np.nan, inplace=True)

In [ ]:
df.vat.value_counts(dropna=False)

In [ ]:
df.vat.isnull().sum()

In [ ]:
df.km

In [ ]:
df["km"] = df.km.str.replace(",","").str.replace(" km", "").str.replace("-", "0")

In [ ]:
df.km.replace("0",np.NaN, inplace=True)

In [ ]:
df["km"] = df.km.astype(float)

In [ ]:
df.km.isnull().sum()

In [ ]:
df.km.value_counts(dropna=False).sort_index(ascending=True)

In [ ]:
df.info()

In [ ]:
df.to_json('scout_car_version_1.json')

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_json('scout_car_version_1.json')

In [ ]:
df.info()

In [ ]:
df["registration"].value_counts(dropna=False)

In [ ]:
df["registration"] = df.registration.str.replace("-/-","")

In [ ]:
df["registration"] = pd.to_datetime(df.registration)

In [ ]:
df["registration"].value_counts(dropna=False).sort_index()

In [ ]:
df.prev_owner.value_counts(dropna=False)

In [ ]:
df["prev_owner"] = df.prev_owner.str.replace("1 previous owner","1").str.replace("2 previous owners","2").str.replace("3 previous owners","3").str.replace("4 previous owners","4")

In [ ]:
df["prev_owner"] = df.prev_owner.astype(float)

In [ ]:
df["prev_owner"].value_counts(dropna=False).sort_index()

In [ ]:
df.kw.value_counts(dropna=False)

In [ ]:
del df["kw"]

In [ ]:
df.hp.value_counts(dropna=False).sort_index()

In [ ]:
df["hp"] = df.hp.str.replace(" kW","").str.replace("-", "0").astype(float)

In [ ]:
df["hp"]  = df["hp"].replace(0, np.nan)

In [ ]:
df.hp.value_counts(dropna=False).sort_index()

In [ ]:
df.to_json('scout_car_version_1_1.json')

In [ ]:
df = pd.read_json('scout_car_version_1_1.json')

In [ ]:
df.gears.value_counts(dropna=False)

In [ ]:
df['gears'] = df['gears'].explode()

In [ ]:
df["gears"] = df.gears.str.strip("\n")

In [ ]:
df["gears"]  = df["gears"].fillna(value=np.nan)

In [ ]:
##df["gears"]  = df["gears"].replace("50",5).astype(float)--kullanılmayacak

In [ ]:
df.gears.value_counts(dropna=False)

In [ ]:
df["gears"].info()

In [ ]:
df.to_json('scout_car_version_1_2.json')
df = pd.read_json('scout_car_version_1_2.json')

In [ ]:
df.country_version.value_counts(dropna=False)

In [ ]:
df['country_version'] = df['country_version'].explode()

In [ ]:
df['country_version'] = df['country_version'].str.strip("\n")

In [ ]:
df['country_version'] = df['country_version'].fillna(value="Unknown")

In [ ]:
df.country_version.value_counts(dropna=False)

In [ ]:
df.to_json('scout_car_version_1_3.json')
df = pd.read_json('scout_car_version_1_3.json')

In [ ]:
df.electricity_consumption.value_counts(dropna=False)
## elektrikli araçlar için kontrol edilecek. Bir fonksiyonu yoksa silinecek.

In [ ]:
df.last_timing_belt_service_date.value_counts(dropna=False)
##atılacak

In [ ]:
df.other_fuel_types.value_counts(dropna=False)
##sil

In [ ]:
df.other_fuel_types.value_counts(dropna=False)

In [ ]:
df.availability =df.availability.str.extract(r'\nin(.*)\n', expand=False)
df.availability =df.availability.str.extract(r'(\d)', expand=False)

In [ ]:
df.availability.value_counts(dropna=False)

In [ ]:
df['available_from'] =df['available_from'].str.extract(r'\n(.*)\n', expand=False)
df['available_from'] = pd.to_datetime(df['available_from'])

In [ ]:
df.available_from.value_counts(dropna=False)

In [ ]:
df.last_service_date.value_counts(dropna=False)

In [ ]:
df['last_service_date_1'] = df['last_service_date']

In [ ]:
df['last_service_date_1'] = df['last_service_date_1'].iloc[1]

In [ ]:
df['last_service_date_1'].value_counts(dropna=False)

In [ ]:
df.co2_emission.value_counts()

In [ ]:
df.full_service.value_counts().sample(10)

In [ ]:
df.non_smoking_vehicle.value_counts()

# PART- 2 `( Handling With Missing Vales )`

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats

In [ ]:
df = pd.read_csv("autoscout.csv")

In [ ]:
indTest = stats.ttest_ind(price, soil2,  nan_policy='omit')
indTest

In [ ]:
df.drive_chain.value_counts(dropna=False)

In [ ]:
df.cylinders.value_counts(dropna=False)

In [ ]:
df.displacement.describe()

In [ ]:
df.displacement.isnull().sum()

In [ ]:
df.gears.value_counts(dropna=False)

In [ ]:
df.weight.sort_values()

In [ ]:
df.weight.describe()

In [ ]:
df.body_color.value_counts()

In [ ]:
df.body_type.value_counts()

In [ ]:
df.co2_emission.describe()

In [ ]:
df.prev_owner.value_counts(dropna=False)

In [ ]:
df.emission_class.value_counts(dropna=False)

In [ ]:
df.comfort_convenience.value_counts()

In [ ]:
df.entertainment_media.value_counts(dropna=False)

In [ ]:
df.extras.value_counts(dropna=False)

In [ ]:
df.emission_label.value_counts(dropna=False)

In [ ]:
df.country_version.value_counts(dropna=False)

In [ ]:
df.electricity_consumption.value_counts(dropna=False)

In [ ]:
df.last_service_date.value_counts(dropna=False)

# FILL MISSING

In [596]:
df = pd.read_csv("autoscout_part1_2.csv")

In [548]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15919 entries, 0 to 15918
Data columns (total 41 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   make_model               15919 non-null  object
 1   body_type                15859 non-null  object
 2   price                    15919 non-null  int64
 3   vat                      11406 non-null  object
 4   km                       15919 non-null  int64
 5   registration             14322 non-null  object
 6   hp                       15831 non-null  float64
 7   type                     15917 non-null  object
 8   previous_owners          9254 non-null   float64
 9   warranty                 4853 non-null   float64
 10  first_registration       14322 non-null  object
 11  body_color               15322 non-null  object
 12  paint_type               10147 non-null  object
 13  nr_of_doors              15707 non-null  float64
 14  nr_of_seats              14942 non-null  float64
 15  gearing_type             15919 non-null  object
 16  displacement             15423 non-null  float64
 17  cylinders                10239 non-null  float64
 18  weight                   8945 non-null   float64
 19  drive_chain              9061 non-null   object
 20  fuel                     15919 non-null  object
 21  co2_emission             13484 non-null  float64
 22  emission_class           12994 non-null  object
 23  comfort_convenience      14999 non-null  object
 24  entertainment_media      14545 non-null  object
 25  extras                   12957 non-null  object
 26  safety_security          14937 non-null  object
 27  emission_label           7944 non-null   float64
 28  gears                    11207 non-null  float64
 29  country_version          15919 non-null  object
 30  electricity_consumption  137 non-null    object
 31  last_service_date        566 non-null    object
 32  availability             635 non-null    float64
 33  available_from           272 non-null    object
 34  upholstery_type          11416 non-null  object
 35  upholstery_colors        10897 non-null  object
 36  comb_consumption         13886 non-null  float64
 37  city_consumption         13483 non-null  float64
 38  country_consumption      13543 non-null  float64
 39  next_inspection          3535 non-null   object
 40  inspection_new           3932 non-null   object
dtypes: float64(15), int64(2), object(24)
memory usage: 5.0+ MB

In [549]:
df = pd.concat([df, pd.get_dummies(df.body_type, prefix="bt" )], axis=1)

In [550]:
df = pd.concat([df, pd.get_dummies(df.body_color, prefix="bt" )], axis=1)

In [551]:
df = pd.concat([df, pd.get_dummies(df.paint_type, prefix="bt" )], axis=1)

In [552]:
df.corr(method ='pearson')

,price,km,hp,previous_owners,warranty,nr_of_doors,nr_of_seats,displacement,cylinders,weight,...,bt_Grey,bt_Orange,bt_Red,bt_Silver,bt_Violet,bt_White,bt_Yellow,bt_Metallic,bt_Perl effect,bt_Uni/basic
price,1.000000,-0.400100,0.693892,-0.119186,0.203521,0.164094,0.257343,0.219811,-0.006954,0.419661,...,0.059281,0.000273,-0.079709,-0.071672,0.022710,-0.057871,0.045680,0.098176,-0.006813,-0.005249
km,-0.400100,1.000000,-0.000328,0.084301,-0.269317,-0.001613,-0.008608,0.274396,0.222700,0.158633,...,0.007787,-0.008124,-0.047344,0.041504,0.026755,-0.004097,-0.036022,-0.012642,-0.008326,-0.035956
hp,0.693892,-0.000328,1.000000,-0.002944,0.070703,0.122800,0.295884,0.497327,0.303342,0.586239,...,0.065444,0.009901,-0.077292,-0.013451,0.032612,-0.118663,0.024976,0.120224,-0.012240,-0.053709
previous_owners,-0.119186,0.084301,-0.002944,1.000000,0.053406,-0.181974,0.004423,0.005963,0.049703,0.052477,...,-0.014787,0.029675,0.012660,0.009030,0.023160,0.000244,-0.017712,-0.033098,-0.004521,0.008124
warranty,0.203521,-0.269317,0.070703,0.053406,1.000000,-0.029053,0.054084,-0.094217,-0.192534,-0.030430,...,-0.028915,NaN,0.027809,0.001706,-0.018081,0.013699,-0.004506,0.017557,-0.008762,-0.042503
nr_of_doors,0.164094,-0.001613,0.122800,-0.181974,-0.029053,1.000000,0.102182,0.069574,0.064377,0.166571,...,0.062693,-0.021193,-0.065969,0.018840,0.011543,-0.031335,-0.002532,0.013215,0.009511,0.019206
nr_of_seats,0.257343,-0.008608,0.295884,0.004423,0.054084,0.102182,1.000000,0.158493,0.228297,0.297760,...,0.082686,0.001450,-0.034110,0.015393,0.035876,-0.103455,-0.006644,0.084105,NaN,-0.028581
displacement,0.219811,0.274396,0.497327,0.005963,-0.094217,0.069574,0.158493,1.000000,0.624423,0.562384,...,0.079298,0.009694,-0.107400,0.041336,0.011355,-0.088111,-0.036778,0.051141,-0.007583,-0.026626
cylinders,-0.006954,0.222700,0.303342,0.049703,-0.192534,0.064377,0.228297,0.624423,1.000000,0.264439,...,0.072700,0.006820,-0.073738,0.055178,0.011690,-0.059825,-0.047559,-0.009255,NaN,-0.029562
weight,0.419661,0.158633,0.586239,0.052477,-0.030430,0.166571,0.297760,0.562384,0.264439,1.000000,...,0.069727,0.005458,-0.079885,0.028852,0.052953,-0.093294,-0.027422,0.052288,NaN,-0.041122
co2_emission,0.022711,-0.012875,0.047290,0.008665,-0.010067,-0.002386,0.021478,0.019135,0.030853,0.273844,...,0.002296,0.000107,-0.007026,-0.007089,-0.000481,-0.007222,-0.001441,0.004738,NaN,-0.004685
emission_label,-0.103842,0.060667,0.047740,0.013848,0.070539,-0.104837,0.019258,0.016295,0.048327,0.013554,...,0.001202,0.003675,0.028562,-0.032433,0.003675,-0.044054,0.006425,0.016874,NaN,-0.045805
gears,0.488886,-0.035845,0.430052,-0.029967,0.010634,0.109322,0.096465,0.281072,0.129086,0.316745,...,0.059947,0.001188,-0.069213,0.001564,0.006123,-0.066161,0.022503,0.071374,-0.002491,-0.028639
availability,0.136293,-0.376403,0.114920,-0.172937,0.523166,0.092346,-0.079656,-0.009124,-0.018297,0.109160,...,-0.350104,NaN,-0.131658,-0.152888,-0.057654,0.048442,-0.060635,-0.518103,NaN,NaN
comb_consumption,0.165446,-0.198226,0.216658,-0.030450,0.078276,-0.030988,0.141768,0.006489,0.070725,0.033537,...,0.029585,0.002437,0.019444,-0.009503,-0.004066,-0.047298,0.006238,0.024914,NaN,-0.001868
city_consumption,0.166502,-0.234106,0.263825,-0.019289,0.107655,-0.067300,0.141754,-0.005315,0.084872,0.008415,...,0.030403,0.003430,0.024463,-0.010005,-0.012865,-0.061799,0.011806,0.057606,NaN,-0.027262
country_consumption,0.209249,-0.221756,0.227635,-0.055688,0.091114,-0.022321,0.153631,0.015889,0.067559,0.047925,...,0.037705,0.002845,0.008789,-0.023074,-0.008855,-0.033632,0.007967,0.026364,NaN,0.012109
bt_Compact,-0.188649,-0.119184,-0.300695,0.056346,0.030506,-0.227569,-0.105516,-0.231499,-0.123365,-0.322876,...,-0.050294,0.004660,0.091143,-0.058074,-0.016721,0.031666,0.033188,0.011387,-0.009650,-0.060154
bt_Convertible,0.030012,-0.006893,0.030067,-0.003916,-0.005396,-0.079800,-0.029353,0.025261,0.013643,0.021330,...,-0.005150,-0.000308,0.017912,-0.007617,-0.000754,0.008805,-0.001271,-0.005311,-0.000435,-0.003347
bt_Coupe,-0.020390,-0.004053,-0.013587,-0.009049,0.005341,-0.077664,-0.014938,-0.010767,0.003636,-0.025962,...,-0.001931,-0.000544,0.023339,0.012571,-0.001334,-0.009087,-0.002248,-0.017545,-0.000770,0.004944
bt_Off-Road,-0.007190,-0.027229,0.007508,-0.017434,-0.055178,0.029924,0.019823,0.042893,0.033833,0.019140,...,-0.018768,-0.000816,-0.015027,-0.009733,-0.001999,0.041442,-0.003368,-0.042422,-0.001154,0.107386
bt_Other,-0.070269,-0.025812,-0.038713,-0.016577,0.013312,0.039377,0.005594,-0.012378,0.049816,-0.042673,...,0.008104,-0.001870,-0.006786,0.016959,-0.004583,-0.011509,-0.007722,0.013111,-0.002645,-0.007467
bt_Sedans,-0.038178,-0.037934,-0.143555,-0.064769,-0.039594,0.075266,-0.135491,-0.082128,-0.135034,-0.157754,...,-0.027004,-0.004479,0.024259,0.005505,-0.022192,0.052109,0.003737,-0.061779,0.006611,0.084089
bt_Station wagon,0.045241,0.169946,0.282822,0.016380,0.054492,0.071290,0.062581,0.225198,0.188953,0.288240,...,0.038852,0.003632,-0.082251,0.071530,-0.004567,-0.106387,-0.025049,0.076606,0.005136,-0.050054
bt_Transporter,-0.012670,0.044028,0.010690,0.001002,-0.066167,0.027813,-0.100117,0.019235,0.030849,0.162511,...,-0.000768,-0.001024,-0.008163,-0.011418,0.022701,0.037542,-0.004227,-0.031590,-0.001448,0.006277
bt_Van,0.394990,-0.011891,0.359436,0.031984,-0.015839,0.081014,0.420679,0.172761,0.109733,0.363264,...,0.081039,-0.003123,-0.057522,-0.042929,0.087424,0.000333,-0.012894,0.008518,-0.004416,-0.012070
bt_Beige,-0.013813,0.052322,0.004129,0.002183,-0.015976,0.023128,0.039367,0.006214,0.006064,0.050984,...,-0.043916,-0.001135,-0.020902,-0.028076,-0.002781,-0.043120,-0.004686,0.011882,-0.001605,-0.001856
bt_Black,0.067659,0.063776,0.069444,-0.018626,-0.034466,-0.003639,0.021883,0.039587,-0.008651,0.018286,...,-0.294712,-0.007615,-0.140272,-0.188414,-0.018661,-0.289368,-0.031444,0.106517,-0.010770,-0.016870
bt_Blue,-0.037404,-0.039451,-0.057512,0.004265,0.046558,-0.048155,-0.017073,-0.033713,-0.021771,-0.063986,...,-0.166995,-0.004315,-0.079483,-0.106763,-0.010574,-0.163967,-0.017817,0.056692,0.005212,-0.021346
bt_Bronze,-0.001477,0.008493,0.002273,-0.003916,-0.009038,0.005370,0.015690,0.006682,0.011814,0.013784,...,-0.010318,-0.000267,-0.004911,-0.006596,-0.000653,-0.010131,-0.001101,-0.004599,-0.000377,-0.002899
bt_Brown,0.011845,0.022977,0.072429,0.024313,0.026437,0.015480,0.018097,0.026597,0.021977,0.073149,...,-0.072253,-0.001867,-0.034390,-0.046193,-0.004575,-0.070943,-0.007709,0.051444,0.021600,-0.020298
bt_Gold,-0.027145,-0.008793,-0.002248,NaN,NaN,-0.011474,0.001184,0.002542,0.006820,-0.005361,...,-0.005956,-0.000154,-0.002835,-0.003808,-0.000377,-0.005848,-0.000635,-0.014175,-0.000218,-0.001673
bt_Green,-0.002666,-0.004496,0.028526,0.028223,-0.008678,-0.011432,0.003337,0.027115,-0.005167,0.026040,...,-0.052517,-0.001357,-0.024996,-0.033575,-0.003325,-0.051565,-0.005603,0.026716,-0.001919,-0.005964
bt_Grey,0.059281,0.007787,0.065444,-0.014787,-0.028915,0.062693,0.082686,0.079298,0.072700,0.069727,...,1.000000,-0.007295,-0.134385,-0.180506,-0.017878,-0.277223,-0.030124,0.178723,-0.010318,-0.014952
bt_Orange,0.000273,-0.008124,0.009901,0.029675,NaN,-0.021193,0.001450,0.009694,0.006820,0.005458,...,-0.007295,1.000000,-0.003472,-0.004664,-0.000462,-0.007163,-0.000778,-0.007955,-0.000267,-0.002049
bt_Red,-0.079709,-0.047344,-0.077292,0.012660,0.027809,-0.065969,-0.034110,-0.107400,-0.073738,-0.079885,...,-0.134385,-0.003472,1.000000,-0.085914,-0.008509,-0.131948,-0.014338,-0.034102,0.008704,0.002062
bt_Silver,-0.071672,0.041504,-0.013451,0.009030,0.001706,0.018840,0.015393,0.041336,0.055178,0.028852,...,-0.180506,-0.004664,-0.085914,1.000000,-0.011430,-0.177234,-0.019259,0.174532,-0.006596,-0.008335
bt_Violet,0.022710,0.026755,0.032612,0.023160,-0.018081,0.011543,0.035876,0.011355,0.011690,0.052953,...,-0.017878,-0.000462,-0.008509,-0.011430,1.000000,-0.017554,-0.001907,0.007398,-0.000653,-0.005022
bt_White,-0.057871,-0.004097,-0.118663,0.000244,0.013699,-0.031335,-0.103455,-0.088111,-0.059825,-0.093294,...,-0.277223,-0.007163,-0.131948,-0.177234,-0.017554,1.000000,-0.029578,-0.387403,0.013544,0.074224
bt_Yellow,0.045680,-0.036022,0.024976,-0.017712,-0.004506,-0.002532,-0.006644,-0.036778,-0.047559,-0.027422,...,-0.030124,-0.000778,-0.014338,-0.019259,-0.001907,-0.029578,1.000000,0.012847,-0.001101,0.006762
bt_Metallic,0.098176,-0.012642,0.120224,-0.033098,0.017557,0.013215,0.084105,0.051141,-0.009255,0.052288,...,0.178723,-0.007955,-0.034102,0.174532,0.007398,-0.387403,0.012847,1.000000,-0.024554,-0.188764
bt_Perl effect,-0.006813,-0.008326,-0.012240,-0.004521,-0.008762,0.009511,NaN,-0.007583,NaN,NaN,...,-0.010318,-0.000267,0.008704,-0.006596,-0.000653,0.013544,-0.001101,-0.024554,1.000000,-0.002899
bt_Uni/basic,-0.005249,-0.035956,-0.053709,0.008124,-0.042503,0.019206,-0.028581,-0.026626,-0.029562,-0.041122,...,-0.014952,-0.002049,0.002062,-0.008335,-0.005022,0.074224,0.006762,-0.188764,-0.002899,1.000000

In [553]:
df["current_date"] = "2019-12-31"

In [554]:
df["current_date"] = pd.to_datetime(df["current_date"])
df["registration"]= pd.to_datetime(df["registration"])

In [555]:
df["age"] = df["current_date"].dt.year - df["registration"].dt.year

In [556]:
df.age

0        3.0
1        2.0
2        3.0
3        3.0
4        3.0
        ...
15914    NaN
15915    0.0
15916    0.0
15917    0.0
15918    0.0
Name: age, Length: 15919, dtype: float64

In [557]:
df.groupby("make_model")["body_type"].value_counts(dropna=False)

make_model      body_type
Audi A1         Sedans           1538
                Compact          1039
                Station wagon      21
                Other              13
                Coupe               2
                Van                 1
Audi A2         Off-Road            1
Audi A3         Sedans           2598
                Station wagon     282
                Compact           182
                Other              16
                Convertible         8
                NaN                 7
                Coupe               4
Opel Astra      Station wagon    1211
                Sedans           1053
                Compact           185
                Other              67
                NaN                 7
                Coupe               2
                Off-Road            1
Opel Corsa      Compact          1230
                Sedans            875
                Other              87
                Coupe              13
                Transporter         7
                Off-Road            3
                NaN                 2
                Van                 2
Opel Insignia   Station wagon    1611
                Sedans            900
                Other              48
                Compact            27
                Off-Road            7
                NaN                 3
                Coupe               1
                Van                 1
Renault Clio    Sedans            918
                Compact           484
                Station wagon     337
                Other              51
                Transporter        29
                NaN                15
                Off-Road            2
                Van                 2
                Coupe               1
Renault Duster  Off-Road           34
Renault Espace  Van               777
                Station wagon      91
                Transporter        52
                NaN                26
                Sedans             21
                Off-Road            8
                Other               8
                Compact             6
                Coupe               2
Name: body_type, dtype: int64

In [558]:
f = lambda x: x.mode().iloc[0]
df["body_type"] = df["body_type"].fillna(df.groupby("make_model")["body_type"].transform(f))

In [559]:
df.groupby("make_model")["body_type"]

In [560]:
df.vat.value_counts(dropna=False)

VAT deductible      10980
NaN                  4513
Price negotiable      426
Name: vat, dtype: int64

In [561]:
df.vat.fillna("unknown", inplace=True)

In [562]:
df = pd.concat([df, pd.get_dummies(df.vat, prefix="vat" )], axis=1)

In [563]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15919 entries, 0 to 15918
Data columns (total 72 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   make_model               15919 non-null  object
 1   body_type                15919 non-null  object
 2   price                    15919 non-null  int64
 3   vat                      15919 non-null  object
 4   km                       15919 non-null  int64
 5   registration             14322 non-null  datetime64[ns]
 6   hp                       15831 non-null  float64
 7   type                     15917 non-null  object
 8   previous_owners          9254 non-null   float64
 9   warranty                 4853 non-null   float64
 10  first_registration       14322 non-null  object
 11  body_color               15322 non-null  object
 12  paint_type               10147 non-null  object
 13  nr_of_doors              15707 non-null  float64
 14  nr_of_seats              14942 non-null  float64
 15  gearing_type             15919 non-null  object
 16  displacement             15423 non-null  float64
 17  cylinders                10239 non-null  float64
 18  weight                   8945 non-null   float64
 19  drive_chain              9061 non-null   object
 20  fuel                     15919 non-null  object
 21  co2_emission             13484 non-null  float64
 22  emission_class           12994 non-null  object
 23  comfort_convenience      14999 non-null  object
 24  entertainment_media      14545 non-null  object
 25  extras                   12957 non-null  object
 26  safety_security          14937 non-null  object
 27  emission_label           7944 non-null   float64
 28  gears                    11207 non-null  float64
 29  country_version          15919 non-null  object
 30  electricity_consumption  137 non-null    object
 31  last_service_date        566 non-null    object
 32  availability             635 non-null    float64
 33  available_from           272 non-null    object
 34  upholstery_type          11416 non-null  object
 35  upholstery_colors        10897 non-null  object
 36  comb_consumption         13886 non-null  float64
 37  city_consumption         13483 non-null  float64
 38  country_consumption      13543 non-null  float64
 39  next_inspection          3535 non-null   object
 40  inspection_new           3932 non-null   object
 41  bt_Compact               15919 non-null  uint8
 42  bt_Convertible           15919 non-null  uint8
 43  bt_Coupe                 15919 non-null  uint8
 44  bt_Off-Road              15919 non-null  uint8
 45  bt_Other                 15919 non-null  uint8
 46  bt_Sedans                15919 non-null  uint8
 47  bt_Station wagon         15919 non-null  uint8
 48  bt_Transporter           15919 non-null  uint8
 49  bt_Van                   15919 non-null  uint8
 50  bt_Beige                 15919 non-null  uint8
 51  bt_Black                 15919 non-null  uint8
 52  bt_Blue                  15919 non-null  uint8
 53  bt_Bronze                15919 non-null  uint8
 54  bt_Brown                 15919 non-null  uint8
 55  bt_Gold                  15919 non-null  uint8
 56  bt_Green                 15919 non-null  uint8
 57  bt_Grey                  15919 non-null  uint8
 58  bt_Orange                15919 non-null  uint8
 59  bt_Red                   15919 non-null  uint8
 60  bt_Silver                15919 non-null  uint8
 61  bt_Violet                15919 non-null  uint8
 62  bt_White                 15919 non-null  uint8
 63  bt_Yellow                15919 non-null  uint8
 64  bt_Metallic              15919 non-null  uint8
 65  bt_Perl effect           15919 non-null  uint8
 66  bt_Uni/basic             15919 non-null  uint8
 67  current_date             15919 non-null  datetime64[ns]
 68  age                      14322 non-null  float64
 69  vat_Price negotiable     15919 non-null  uint8
 70  vat_VAT deductible       15919 non-null  uint8
 71  vat_unknown              15919 non-null  uint8
dtypes: datetime64[ns](2), float64(16), int64(2), object(23), uint8(29)
memory usage: 5.7+ MB

In [564]:
df["vat_Price negotiable"].value_counts(dropna=False)

0    15493
1      426
Name: vat_Price negotiable, dtype: int64

In [565]:
df["vat_VAT deductible"].value_counts(dropna=False)

1    10980
0     4939
Name: vat_VAT deductible, dtype: int64

In [566]:
df.vat.isnull().sum()

0

In [567]:
df.registration.value_counts(dropna=False)

NaT           1597
2018-03-01     695
2019-02-01     585
2018-05-01     572
2019-03-01     543
2019-01-01     541
2018-04-01     541
2018-02-01     539
2016-03-01     536
2016-04-01     532
2018-06-01     532
2018-01-01     511
2019-04-01     506
2016-02-01     472
2017-03-01     471
2016-05-01     459
2016-06-01     452
2019-05-01     440
2017-06-01     409
2017-05-01     404
2018-07-01     396
2017-04-01     380
2016-01-01     376
2017-02-01     368
2017-01-01     306
2018-08-01     285
2019-06-01     224
2017-07-01     215
2017-11-01     180
2016-07-01     176
2016-10-01     160
2017-10-01     154
2017-09-01     149
2016-11-01     142
2018-09-01     141
2016-09-01     141
2016-12-01     134
2017-12-01     123
2017-08-01     114
2018-11-01     110
2018-12-01     103
2018-10-01      97
2016-08-01      94
2019-07-01       6
2019-09-01       5
2019-08-01       1
2019-11-01       1
2019-12-01       1
Name: registration, dtype: int64

In [568]:
df.groupby("make_model")["hp"].value_counts(dropna=False)

make_model      hp
Audi A1         85.0     890
                70.0     791
                66.0     465
                92.0     172
                60.0     156
                        ...
Renault Espace  167.0      2
                115.0      1
                120.0      1
                149.0      1
                150.0      1
Name: hp, Length: 148, dtype: int64

In [569]:
df.groupby("cylinders")["hp"].value_counts(dropna=False)

cylinders  hp
1.0        66.0       1
2.0        100.0      1
           147.0      1
3.0        85.0     755
           70.0     525
                   ...
5.0        54.0       1
           85.0       1
6.0        100.0      3
8.0        70.0       1
           117.0      1
Name: hp, Length: 82, dtype: int64

In [570]:
df['hp'] = df['hp'].fillna(df.groupby('price')['hp'].transform('mean'))

In [571]:
df["hp"].isnull().sum()

8

In [572]:
f = lambda x: x.median()
df["hp"] = df["hp"].fillna(df.groupby("price")["hp"].transform(f))

In [573]:
df.to_csv("autoscout_part1_3.csv")

In [574]:
df = pd.read_csv("autoscout_part1_3.csv")

In [575]:
df.type.value_counts(dropna=False)

Used              11096
New                1650
Pre-registered     1364
Employee's car     1011
Demonstration       796
NaN                   2
Name: type, dtype: int64

In [576]:
df["type"].fillna(df["type"].mode().iloc[0], inplace=True)

In [577]:
df.type.value_counts(dropna=False)

Used              11098
New                1650
Pre-registered     1364
Employee's car     1011
Demonstration       796
Name: type, dtype: int64

In [578]:
df.paint_type.value_counts(dropna=False)

Metallic       9794
NaN            5772
Uni/basic       347
Perl effect       6
Name: paint_type, dtype: int64

In [579]:
df.groupby("previous_owners")["km"].median()

previous_owners
0.0        1.0
1.0    23371.5
2.0    36253.5
3.0    45000.0
4.0    38350.0
Name: km, dtype: float64

In [580]:
df.previous_owners.value_counts(dropna=False)

1.0    8294
NaN    6665
2.0     778
0.0     163
3.0      17
4.0       2
Name: previous_owners, dtype: int64

In [581]:
f = lambda x: x.ffill()
df["previous_owners"] = df["previous_owners"].fillna(df.groupby("km")["previous_owners"].transform(f))

In [582]:
f = lambda x: x.bfill()
df["previous_owners"] = df["previous_owners"].fillna(df.groupby("km")["previous_owners"].transform(f))

In [525]:
f = lambda x: x.mode().iloc[0]
df["previous_owners"] = df["previous_owners"].fillna(df.groupby("km")["previous_owners"].transform(f))

IndexError: single positional indexer is out-of-bounds

def fill(df, group_col1, group_col2, col_name, method): # method can be "mode" or "median" or "ffill"
    if method == "mode":
        for group1 in list(df[group_col1].unique()):
            for group2 in list(df[group_col2].unique()):
                cond1 = df[group_col1]==group1
                cond2 = (df[group_col1]==group1) & (df[group_col2]==group2)
                mode1 = list(df[cond1][col_name].mode())
                mode2 = list(df[cond2][col_name].mode())
                if mode2 != []:
                    df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(df[cond2][col_name].mode()[0])
                elif mode1 != []:
                    df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(df[cond1][col_name].mode()[0])
                else:
                    df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(df[col_name].mode()[0])
                
    elif method == "median":
        for group1 in list(df[group_col1].unique()):
            for group2 in list(df[group_col2].unique()):
                cond1 = df[group_col1]==group1
                cond2 = (df[group_col1]==group1) & (df[group_col2]==group2)
                df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(df[cond2][col_name].median()).fillna(df[cond1][col_name].median()).fillna(df[col_name].median())
                
    elif method == "ffill":           
        for group1 in list(df[group_col1].unique()):
            for group2 in list(df[group_col2].unique()):
                cond2 = (df[group_col1]==group1) & (df[group_col2]==group2)
                df.loc[cond2, col_name] = df.loc[cond2, col_name].fillna(method="ffill").fillna(method="bfill")
                
        for group1 in list(df[group_col1].unique()):
            cond1 = df[group_col1]==group1
            df.loc[cond1, col_name] = df.loc[cond1, col_name].fillna(method="ffill").fillna(method="bfill")            
           
        df[col_name] = df[col_name].fillna(method="ffill").fillna(method="bfill")
    
    print("Number of NaN : ",df[col_name].isnull().sum())
    print("------------------")
    print(df[col_name].value_counts(dropna=False))

In [583]:
df.corr(method ='pearson')

,Unnamed: 0,price,km,hp,previous_owners,warranty,nr_of_doors,nr_of_seats,displacement,cylinders,...,bt_Violet,bt_White,bt_Yellow,bt_Metallic,bt_Perl effect,bt_Uni/basic,age,vat_Price negotiable,vat_VAT deductible,vat_unknown
Unnamed: 0,1.000000,0.041039,-0.061112,0.238306,-0.005809,-0.017917,0.120981,0.328757,0.175019,0.426629,...,0.033763,-0.005593,-0.029194,-0.049691,0.000345,-0.004925,-0.119385,-0.019034,-0.021978,0.029374
price,0.041039,1.000000,-0.400100,0.695373,-0.136711,0.203521,0.164094,0.257343,0.219811,-0.006954,...,0.022710,-0.057871,0.045680,0.098176,-0.006813,-0.005249,-0.449787,-0.043167,0.139014,-0.127228
km,-0.061112,-0.400100,1.000000,-0.002063,0.187352,-0.269317,-0.001613,-0.008608,0.274396,0.222700,...,0.026755,-0.004097,-0.036022,-0.012642,-0.008326,-0.035956,0.735115,0.062013,-0.107658,0.088297
hp,0.238306,0.695373,-0.002063,1.000000,0.000203,0.071129,0.122520,0.295830,0.496877,0.303163,...,0.032645,-0.119760,0.024898,0.119699,-0.012219,-0.053941,-0.065699,0.003833,0.060851,-0.063833
previous_owners,-0.005809,-0.136711,0.187352,0.000203,1.000000,-0.003115,-0.149821,-0.006898,0.077344,0.085511,...,0.014911,-0.022145,-0.023483,0.020679,-0.001211,-0.020631,0.250217,0.116416,-0.174163,0.135112
warranty,-0.017917,0.203521,-0.269317,0.071129,-0.003115,1.000000,-0.029053,0.054084,-0.094217,-0.192534,...,-0.018081,0.013699,-0.004506,0.017557,-0.008762,-0.042503,-0.292660,-0.027253,0.188384,-0.184887
nr_of_doors,0.120981,0.164094,-0.001613,0.122520,-0.149821,-0.029053,1.000000,0.102182,0.069574,0.064377,...,0.011543,-0.031335,-0.002532,0.013215,0.009511,0.019206,-0.073096,0.002316,-0.019341,0.019020
nr_of_seats,0.328757,0.257343,-0.008608,0.295830,-0.006898,0.054084,0.102182,1.000000,0.158493,0.228297,...,0.035876,-0.103455,-0.006644,0.084105,NaN,-0.028581,-0.087182,-0.025249,0.056735,-0.049096
displacement,0.175019,0.219811,0.274396,0.496877,0.077344,-0.094217,0.069574,0.158493,1.000000,0.624423,...,0.011355,-0.088111,-0.036778,0.051141,-0.007583,-0.026626,0.184826,0.032124,-0.010293,-0.001045
cylinders,0.426629,-0.006954,0.222700,0.303163,0.085511,-0.192534,0.064377,0.228297,0.624423,1.000000,...,0.011690,-0.059825,-0.047559,-0.009255,NaN,-0.029562,0.168909,0.009701,-0.085670,0.084473
weight,0.224299,0.419661,0.158633,0.586153,0.081047,-0.030430,0.166571,0.297760,0.562384,0.264439,...,0.052953,-0.093294,-0.027422,0.052288,NaN,-0.041122,0.080077,-0.015904,0.063929,-0.058854
co2_emission,0.037493,0.022711,-0.012875,0.047277,0.006678,-0.010067,-0.002386,0.021478,0.019135,0.030853,...,-0.000481,-0.007222,-0.001441,0.004738,NaN,-0.004685,-0.015768,-0.006884,0.021738,-0.019824
emission_label,0.122619,-0.103842,0.060667,0.047744,0.046694,0.070539,-0.104837,0.019258,0.016295,0.048327,...,0.003675,-0.044054,0.006425,0.016874,NaN,-0.045805,0.101679,0.012685,0.014220,-0.017943
gears,-0.163733,0.488886,-0.035845,0.431067,-0.004715,0.010634,0.109322,0.096465,0.281072,0.129086,...,0.006123,-0.066161,0.022503,0.071374,-0.002491,-0.028639,-0.074455,0.006394,0.051663,-0.056020
availability,-0.157427,0.136293,-0.376403,0.114920,-0.248179,0.523166,0.092346,-0.079656,-0.009124,-0.018297,...,-0.057654,0.048442,-0.060635,-0.518103,NaN,NaN,-0.348919,-0.049812,0.190411,-0.183204
comb_consumption,0.236294,0.165446,-0.198226,0.216969,-0.053859,0.078276,-0.030988,0.141768,0.006489,0.070725,...,-0.004066,-0.047298,0.006238,0.024914,NaN,-0.001868,-0.226596,-0.030171,0.084019,-0.075174
city_consumption,0.277541,0.166502,-0.234106,0.263606,-0.045508,0.107655,-0.067300,0.141754,-0.005315,0.084872,...,-0.012865,-0.061799,0.011806,0.057606,NaN,-0.027262,-0.277524,-0.028118,0.099253,-0.091731
country_consumption,0.249000,0.209249,-0.221756,0.226250,-0.070505,0.091114,-0.022321,0.153631,0.015889,0.067559,...,-0.008855,-0.033632,0.007967,0.026364,NaN,0.012109,-0.297953,-0.031020,0.101325,-0.092753
bt_Compact,-0.100094,-0.188649,-0.119184,-0.299618,-0.017748,0.030506,-0.227569,-0.105516,-0.231499,-0.123365,...,-0.016721,0.031666,0.033188,0.011387,-0.009650,-0.060154,-0.064418,-0.069712,0.062095,-0.038773
bt_Convertible,-0.021704,0.030012,-0.006893,0.029991,0.007979,-0.005396,-0.079800,-0.029353,0.025261,0.013643,...,-0.000754,0.008805,-0.001271,-0.005311,-0.000435,-0.003347,0.004558,0.013650,-0.009197,0.004552
bt_Coupe,0.001188,-0.020390,-0.004053,-0.013571,-0.002372,0.005341,-0.077664,-0.014938,-0.010767,0.003636,...,-0.001334,-0.009087,-0.002248,-0.017545,-0.000770,0.004944,0.021901,0.013084,-0.035128,0.031371
bt_Off-Road,0.077435,-0.007190,-0.027229,0.005427,-0.060851,-0.055178,0.029924,0.019823,0.042893,0.033833,...,-0.001999,0.041442,-0.003368,-0.042422,-0.001154,0.107386,-0.029614,-0.003278,-0.031251,0.033250
bt_Other,0.048141,-0.070269,-0.025812,-0.038021,-0.019378,0.013312,0.039377,0.005594,-0.012378,0.049816,...,-0.004583,-0.011509,-0.007722,0.013111,-0.002645,-0.007467,-0.032842,-0.019677,-0.122887,0.133178
bt_Sedans,-0.292781,-0.038178,-0.037934,-0.145737,-0.009433,-0.039594,0.075266,-0.135491,-0.082128,-0.135034,...,-0.022192,0.052109,0.003737,-0.061779,0.006611,0.084089,-0.015854,0.057230,-0.058401,0.039450
bt_Station wagon,0.203761,0.045241,0.169946,0.281609,0.020766,0.054492,0.071290,0.062581,0.225198,0.188953,...,-0.004567,-0.106387,-0.025049,0.076606,0.005136,-0.050054,0.087609,0.000860,0.094689,-0.097498
bt_Transporter,0.103481,-0.012670,0.044028,0.010638,0.023988,-0.066167,0.027813,-0.100117,0.019235,0.030849,...,0.022701,0.037542,-0.004227,-0.031590,-0.001448,0.006277,0.054985,0.024386,-0.047064,0.039575
bt_Van,0.368455,0.394990,-0.011891,0.359978,0.032173,-0.015839,0.081014,0.420679,0.172761,0.109733,...,0.087424,0.000333,-0.012894,0.008518,-0.004416,-0.012070,-0.014584,-0.003516,-0.039602,0.041907
bt_Beige,0.056784,-0.013813,0.052322,0.005477,0.014338,-0.015976,0.023128,0.039367,0.006214,0.006064,...,-0.002781,-0.043120,-0.004686,0.011882,-0.001605,-0.001856,0.056363,0.028972,-0.004123,-0.006143
bt_Black,-0.075289,0.067659,0.063776,0.069898,0.004045,-0.034466,-0.003639,0.021883,0.039587,-0.008651,...,-0.018661,-0.289368,-0.031444,0.106517,-0.010770,-0.016870,0.025507,0.008059,0.038711,-0.042620
bt_Blue,-0.051254,-0.037404,-0.039451,-0.057539,0.019463,0.046558,-0.048155,-0.017073,-0.033713,-0.021771,...,-0.010574,-0.163967,-0.017817,0.056692,0.005212,-0.021346,-0.044507,-0.015370,0.036547,-0.032008
bt_Bronze,0.006792,-0.001477,0.008493,0.002261,0.007979,-0.009038,0.005370,0.015690,0.006682,0.011814,...,-0.000653,-0.010131,-0.001101,-0.004599,-0.000377,-0.002899,0.018205,-0.003220,-0.021956,0.023689
bt_Brown,0.016762,0.011845,0.022977,0.072268,0.029919,0.026437,0.015480,0.018097,0.026597,0.021977,...,-0.004575,-0.070943,-0.007709,0.051444,0.021600,-0.020298,0.029120,0.018269,0.000676,-0.007236
bt_Gold,-0.001534,-0.027145,-0.008793,-0.002248,NaN,NaN,-0.011474,0.001184,0.002542,0.006820,...,-0.000377,-0.005848,-0.000635,-0.014175,-0.000218,-0.001673,-0.005952,-0.001859,-0.016713,0.017820
bt_Green,-0.006368,-0.002666,-0.004496,0.028424,0.012723,-0.008678,-0.011432,0.003337,0.027115,-0.005167,...,-0.003325,-0.051565,-0.005603,0.026716,-0.001919,-0.005964,-0.000204,0.011449,0.012181,-0.016602
bt_Grey,0.087335,0.059281,0.007787,0.066706,0.027753,-0.028915,0.062693,0.082686,0.079298,0.072700,...,-0.017878,-0.277223,-0.030124,0.178723,-0.010318,-0.014952,-0.023586,0.000192,-0.008371,0.008524
bt_Orange,0.000610,0.000273,-0.008124,0.009874,0.015216,NaN,-0.021193,0.001450,0.009694,0.006820,...,-0.000462,-0.007163,-0.000778,-0.007955,-0.000267,-0.002049,0.005022,-0.002277,-0.010578,0.011672
bt_Red,-0.016520,-0.079709,-0.047344,-0.078340,0.015857,0.027809,-0.065969,-0.034110,-0.107400,-0.073738,...,-0.008509,-0.131948,-0.014338,-0.034102,0.008704,0.002062,-0.020072,-0.002636,-0.038894,0.040865
bt_Silver,0.001641,-0.071672,0.041504,-0.013543,0.026384,0.001706,0.018840,0.015393,0.041336,0.055178,...,-0.011430,-0.177234,-0.019259,0.174532,-0.006596,-0.008335,0.021797,0.001183,0.011145,-0.011862
bt_Violet,0.033763,0.022710,0.026755,0.032645,0.014911,-0.018081,0.011543,0.035876,0.011355,0.011690,...,1.000000,-0.017554,-0.001907,0.007398,-0.000653,-0.005022,0.031545,0.052332,-0.034003,0.016162
bt_White,-0.005593,-0.057871,-0.004097,-0.119760,-0.022145,0.013699,-0.031335,-0.103455,-0.088111,-0.059825,...,-0.017554,1.000000,-0.029578,-0.387403,0.013544,0.074224,0.009848,0.000810,-0.037503,0.038204
bt_Yellow,-0.029194,0.045680,-0.036022,0.024898,-0.023483,-0.004506,-0.002532,-0.006644,-0.036778,-0.047559,...,-0.001907,-0.029578,1.000000,0.012847,-0.001101,0.006762,-0.032808,-0.009401,0.021202,-0.018396
bt_Metallic,-0.049691,0.098176,-0.012642,0.119699,0.020679,0.017557,0.013215,0.084105,0.051141,-0.009255,...,0.007398,-0.387403,0.012847,1.000000,-0.024554,-0.188764,-0.060094,-0.013674,0.155367,-0.154574
bt_Perl effect,0.000345,-0.006813,-0.008326,-0.012219,-0.001211,-0.008762,0.009511,NaN,-0.007583,NaN,...,-0.000653,0.013544,-0.001101,-0.024554,1.000000,-0.002899,-0.002471,-0.003220,-0.014960,0.016508
bt_Uni/basic,-0.004925,-0.005249,-0.035956,-0.053941,-0.020631,-0.042503,0.019206,-0.028581,-0.026626,-0.029562,...,-0.005022,0.074224,0.006762,-0.188764,-0.002899,1.000000,-0.049284,-0.024753,0.004333,0.004416
age,-0.119385,-0.449787,0.735115,-0.065699,0.250217,-0.292660,-0.073096,-0.087182,0.184826,0.168909,...,0.031545,0.009848,-0.032808,-0.060094,-0.002471,-0.049284,1.000000,0.129745,-0.254508,0.213004
vat_Price negotiable,-0.019034,-0.043167,0.062013,0.003833,0.116416,-0.027253,0.002316,-0.025249,0.032124,0.009701,...,0.052332,0.000810,-0.009401,-0.013674,-0.003220,-0.024753,0.129745,1.000000,-0.247240,-0.104304
vat_VAT deductible,-0.021978,0.139014,-0.107658,0.060851,-0.174163,0.188384,-0.019341,0.056735,-0.010293,-0.085670,...,-0.034003,-0.037503,0.021202,0.155367,-0.014960,0.004333,-0.254508,-0.247240,1.000000,-0.937881
vat_unknown,0.029374,-0.127228,0.088297,-0.063833,0.135112,-0.184887,0.019020,-0.049096,-0.001045,0.084473,...,0.016162,0.038204,-0.018396,-0.154574,0.016508,0.004416,0.213004,-0.104304,-0.937881,1.000000

In [584]:
df.hp.value_counts().sort_index()

1.0      20
4.0       1
9.0       1
40.0      2
44.0      1
         ..
195.0     1
228.0     2
239.0     1
270.0     2
294.0    18
Name: hp, Length: 125, dtype: int64

In [585]:
df["paint_type"].value_counts(dropna=False)

Metallic       9794
NaN            5772
Uni/basic       347
Perl effect       6
Name: paint_type, dtype: int64

In [586]:
df["paint_type"].fillna(df["paint_type"].mode().iloc[0], inplace=True)

In [587]:
f = lambda x: x.mode().iloc[0]
df["paint_type"] = df["paint_type"].fillna(df.groupby("make_model")["paint_type"].transform(f))

In [588]:
f = lambda x: x.mode().iloc[0]
df["paint_type"].fillna(df.groupby("make_model")["paint_type"].transform(f))

0        Metallic
1        Metallic
2        Metallic
3        Metallic
4        Metallic
           ...
15914    Metallic
15915    Metallic
15916    Metallic
15917    Metallic
15918    Metallic
Name: paint_type, Length: 15919, dtype: object

In [589]:
df.groupby(["cylinders", "hp", "weight"])["displacement"].value_counts(dropna=False).sort_values()

cylinders  hp     weight  displacement
1.0        66.0   1163.0  1398.0            1
4.0        88.0   1239.0  1197.0            1
                  1199.0  1197.0            1
                  1145.0  1364.0            1
                  1143.0  1197.0            1
                                         ...
           66.0   1199.0  1398.0          162
           118.0  1734.0  1598.0          163
           85.0   1360.0  1598.0          189
           51.0   1163.0  1229.0          212
           66.0   1163.0  1398.0          279
Name: displacement, Length: 889, dtype: int64

In [597]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15919 entries, 0 to 15918
Data columns (total 41 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   make_model               15919 non-null  object
 1   body_type                15859 non-null  object
 2   price                    15919 non-null  int64
 3   vat                      11406 non-null  object
 4   km                       15919 non-null  int64
 5   registration             14322 non-null  object
 6   hp                       15831 non-null  float64
 7   type                     15917 non-null  object
 8   previous_owners          9254 non-null   float64
 9   warranty                 4853 non-null   float64
 10  first_registration       14322 non-null  object
 11  body_color               15322 non-null  object
 12  paint_type               10147 non-null  object
 13  nr_of_doors              15707 non-null  float64
 14  nr_of_seats              14942 non-null  float64
 15  gearing_type             15919 non-null  object
 16  displacement             15423 non-null  float64
 17  cylinders                10239 non-null  float64
 18  weight                   8945 non-null   float64
 19  drive_chain              9061 non-null   object
 20  fuel                     15919 non-null  object
 21  co2_emission             13484 non-null  float64
 22  emission_class           12994 non-null  object
 23  comfort_convenience      14999 non-null  object
 24  entertainment_media      14545 non-null  object
 25  extras                   12957 non-null  object
 26  safety_security          14937 non-null  object
 27  emission_label           7944 non-null   float64
 28  gears                    11207 non-null  float64
 29  country_version          15919 non-null  object
 30  electricity_consumption  137 non-null    object
 31  last_service_date        566 non-null    object
 32  availability             635 non-null    float64
 33  available_from           272 non-null    object
 34  upholstery_type          11416 non-null  object
 35  upholstery_colors        10897 non-null  object
 36  comb_consumption         13886 non-null  float64
 37  city_consumption         13483 non-null  float64
 38  country_consumption      13543 non-null  float64
 39  next_inspection          3535 non-null   object
 40  inspection_new           3932 non-null   object
dtypes: float64(15), int64(2), object(24)
memory usage: 5.0+ MB

In [598]:
df.to_csv('scout_car_version_1_3.csv')

In [647]:
df = pd.read_csv('scout_car_version_1_3.csv')

In [600]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15919 entries, 0 to 15918
Data columns (total 42 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               15919 non-null  int64
 1   make_model               15919 non-null  object
 2   body_type                15859 non-null  object
 3   price                    15919 non-null  int64
 4   vat                      11406 non-null  object
 5   km                       15919 non-null  int64
 6   registration             14322 non-null  object
 7   hp                       15831 non-null  float64
 8   type                     15917 non-null  object
 9   previous_owners          9254 non-null   float64
 10  warranty                 4853 non-null   float64
 11  first_registration       14322 non-null  object
 12  body_color               15322 non-null  object
 13  paint_type               10147 non-null  object
 14  nr_of_doors              15707 non-null  float64
 15  nr_of_seats              14942 non-null  float64
 16  gearing_type             15919 non-null  object
 17  displacement             15423 non-null  float64
 18  cylinders                10239 non-null  float64
 19  weight                   8945 non-null   float64
 20  drive_chain              9061 non-null   object
 21  fuel                     15919 non-null  object
 22  co2_emission             13484 non-null  float64
 23  emission_class           12994 non-null  object
 24  comfort_convenience      14999 non-null  object
 25  entertainment_media      14545 non-null  object
 26  extras                   12957 non-null  object
 27  safety_security          14937 non-null  object
 28  emission_label           7944 non-null   float64
 29  gears                    11207 non-null  float64
 30  country_version          15919 non-null  object
 31  electricity_consumption  137 non-null    object
 32  last_service_date        566 non-null    object
 33  availability             635 non-null    float64
 34  available_from           272 non-null    object
 35  upholstery_type          11416 non-null  object
 36  upholstery_colors        10897 non-null  object
 37  comb_consumption         13886 non-null  float64
 38  city_consumption         13483 non-null  float64
 39  country_consumption      13543 non-null  float64
 40  next_inspection          3535 non-null   object
 41  inspection_new           3932 non-null   object
dtypes: float64(15), int64(3), object(24)
memory usage: 5.1+ MB

In [618]:
f = lambda x: x.median()
df["weight"] = df["weight"].fillna(df.groupby(["make_model", "body_type"])["weight"].transform(f))

In [619]:
df["weight"].isnull().sum()

95

In [646]:
df["emission_class"].fillna(df["emission_class"].mode().iloc[0], inplace=True)

In [ ]:
f = lambda x: x.median()
df["cc_index"] = df["cc_index"].fillna(df.groupby(["make_model"])["cc_index"].transform(f))

In [643]:
df = pd.read_csv('scout_car_version_1_3.csv')

In [644]:
df = pd.concat([df, pd.get_dummies(df.extras, prefix="ex" )], axis=1)

In [645]:
df.head()

,Unnamed: 0,make_model,body_type,price,vat,km,registration,hp,type,previous_owners,...,"ex_'Touch screen', 'Trailer hitch'","ex_'Touch screen', 'Voice Control'","ex_'Touch screen', 'Voice Control', 'Winter tyres'","ex_'Touch screen', 'Winter tyres'",ex_'Trailer hitch',"ex_'Trailer hitch', 'Voice Control'","ex_'Tuned car', 'Voice Control'",ex_'Voice Control',"ex_'Voice Control', 'Winter tyres'",ex_'Winter tyres'
0,0,Audi A1,Sedans,15770,VAT deductible,56013,2016-01-01,66.0,Used,2.0,...,0,0,0,0,0,0,0,0,0,0
1,1,Audi A1,Sedans,14500,Price negotiable,80000,2017-03-01,141.0,Used,NaN,...,0,0,0,0,0,0,0,0,0,0
2,2,Audi A1,Sedans,14640,VAT deductible,83450,2016-02-01,85.0,Used,1.0,...,0,0,0,0,0,0,0,0,0,0
3,3,Audi A1,Sedans,14500,NaN,73000,2016-08-01,66.0,Used,1.0,...,0,0,0,0,0,0,0,0,0,0
4,4,Audi A1,Sedans,16790,NaN,16200,2016-05-01,66.0,Used,1.0,...,0,0,0,0,0,0,0,0,0,0

In [620]:
df["entertainment_media"] = df.entertainment_media.str.lower().str.replace("'", "")

In [642]:
df["em_'On-board computer', 'Sound system', 'USB'"].sum()

2

In [635]:
pd.get_dummies(df["entertainment_media"].apply(pd.Series).stack()).sum(level=0)

                    #pd.get_dummies(s.apply(pd.Series).stack()).sum(level=0)

C:\Users\MHM\AppData\Local\Temp\ipykernel_4712\406149547.py:1: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  df1 = pd.get_dummies(df["entertainment_media"].apply(pd.Series).stack()).sum(level=0)

In [636]:
df1.head()

,bluetooth,"bluetooth, cd player","bluetooth, cd player, digital radio, hands-free equipment","bluetooth, cd player, digital radio, hands-free equipment, mp3, on-board computer, radio","bluetooth, cd player, digital radio, hands-free equipment, mp3, on-board computer, radio, sound system","bluetooth, cd player, digital radio, hands-free equipment, mp3, on-board computer, radio, sound system, television, usb","bluetooth, cd player, digital radio, hands-free equipment, mp3, on-board computer, radio, sound system, usb","bluetooth, cd player, digital radio, hands-free equipment, mp3, on-board computer, radio, usb","bluetooth, cd player, digital radio, hands-free equipment, mp3, on-board computer, sound system, television, usb","bluetooth, cd player, digital radio, hands-free equipment, mp3, on-board computer, sound system, usb",...,"on-board computer, sound system","on-board computer, sound system, usb","on-board computer, usb",radio,"radio, sound system","radio, sound system, usb","radio, usb",sound system,"sound system, usb",usb
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [593]:
df = pd.concat([df, pd.get_dummies(df.entertainment_media, prefix="em" )], axis=1)

In [648]:
df.upholstery_type.value_counts()

Cloth           8423
Part leather    1499
Full leather    1009
Other            368
Velour            60
alcantara         57
Name: upholstery_type, dtype: int64

In [536]:
df["em_index"] = df.em_o

,Unnamed: 0,make_model,body_type,price,vat,km,registration,hp,type,previous_owners,...,"em_'On-board computer', 'Sound system'","em_'On-board computer', 'Sound system', 'USB'","em_'On-board computer', 'USB'",em_'Radio',"em_'Radio', 'Sound system'","em_'Radio', 'Sound system', 'USB'","em_'Radio', 'USB'",em_'Sound system',"em_'Sound system', 'USB'",em_'USB'
0,0,Audi A1,Sedans,15770,VAT deductible,56013,2016-01-01,66.0,Used,2.0,...,0,0,0,0,0,0,0,0,0,0
1,1,Audi A1,Sedans,14500,Price negotiable,80000,2017-03-01,141.0,Used,2.0,...,0,0,0,0,0,0,0,0,0,0
2,2,Audi A1,Sedans,14640,VAT deductible,83450,2016-02-01,85.0,Used,1.0,...,0,0,0,0,0,0,0,0,0,0
3,3,Audi A1,Sedans,14500,unknown,73000,2016-08-01,66.0,Used,1.0,...,0,0,0,0,0,0,0,0,0,0
4,4,Audi A1,Sedans,16790,unknown,16200,2016-05-01,66.0,Used,1.0,...,0,0,0,0,0,0,0,0,0,0

In [649]:
df.groupby([ "comb_consumption", "country_consumption"])["city_consumption"].value_counts(dropna=False)

comb_consumption  country_consumption  city_consumption
0.0               0.0                  0.0                  1
1.0               1.0                  1.0                  1
3.0               2.0                  1.0                  1
                  3.0                  4.0                 53
                                       3.0                  9
                                                           ..
40.0              37.0                 45.0                 2
43.0              3.8                  5.1                  1
50.0              42.0                 64.0                 1
51.0              44.0                 62.0                 4
55.0              4.5                  7.3                  1
Name: city_consumption, Length: 662, dtype: int64

In [650]:
df.city_consumption.isnull().sum()

2436

# PART- 3 `( Handling With Outliers )`

# Final Step (Checking final situation of data via graphs)

## Export dataframe to csv file (without dummy)

In [ ]:
df.to_csv("final_scout_not_dummy.csv", index=False)

# Dummy Operation

## Export dataframe to csv file (dummy)

In [ ]:
df_dummied.to_csv("final_scout_dummy.csv", index=False)